orbs:
  node: circleci/node@2.0.2

version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12.16.0
    working_directory: ~/SCA_Final_Project/app/backend

    steps:
      - checkout:
          path: ~/SCA_Final_Project
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: echo "Running tests"
      - run:
          name: install project dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: run test
          command: npm run test
      - run: npm install
      - run: npm run test

workflows:
  version: 2
    test_build:
      jobs:
        - test
        - build:
          requires:
            - test
