pipeline {
  agent any

  stages {

    stage('Cloning Git') {
      steps {
        git 'https://github.com/deserie-dev/SCA_Final_Project.git'
      }
    }

    stage("Build Backend Docker Image") {
      steps {
        echo 'Building image'
        sh '''
        docker-backend -f docker-backend.yml build
        '''
      }

      steps {
        sh "cd backend"
      }
    }

    stage("Build Frontend Docker Image") {
      steps {
        echo 'Building image'
        sh '''
        docker-frontend -f docker-frontend.yml build
        '''
      }

      steps {
        sh "cd frontend"
      }
    }
  }
}